Update LogisticRegression.py
The following error occurred while trying to implement logistic regression model.
 org.apache.spark.SparkException: Currently, LogisticRegression with ElasticNet in ML package only supports binary classification. Found 12612 in the input dataset.

The given data set requires to implement using multinomial logisitic regression model but in the available spark 2.0.1 version this model is not available.